spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email, openid
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope: public_profile, email
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v2.12/dialog/oauth
            token-uri: https://graph.facebook.com/v2.12/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.width(800)
            user-name-attribute: id
  data:
    redis:
      url: ${REDISCLOUD_URL}
  application:
    name: comments-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.data.redis: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs


